name: Build and Deploy Frontend to Dev Server

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/elcaptain-frontend:${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/elcaptain-frontend:latest

      - name: SSH into Dev Server and Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🧱 Pulling latest frontend image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/elcaptain-frontend:latest

            echo "🛑 Stopping old frontend container if exists..."
            docker stop frontend-container || true
            docker rm frontend-container || true

            echo "🚀 Recreating services with docker-compose..."
            docker-compose -f /home/ec2-user/docker-compose.yaml up -d

            echo "🧹 Cleaning old images..."
            docker image prune -f
